@startuml OasisHotel

class Usuario {
    - id: Long
    - nome: String
    - sobrenome: String
    - email: String
    - senha: String
    - dataNascimento: Date
    - endereco: String
    - cpf: String
}

enum Perfil {
    - Funcionario
    - Cliente
}

class Contato {
    - id: Long
    - telefone: String
}

class Quarto {
    - id: Long
    - nome: String
    - valor: int
    - descricao: String
    - isReservado: boolean
}

class TipoQuarto {
    - id: Long
    - nome: String
}

class Amenidade {
    - id: Long
    - nome: String
}

class Promocao {
    - id: Long
    - nome: String
    - descricao: String
    - dataInicio: Date
    - dataFim: Date
    - valor: double
}

class ReservaQuarto {
    - id: Long
    - checkInDate: Date
    - checkOutDate: Date
    - qtdAdultos: int
    - qtdCrianca: int
}

class Servico {
    - id: Long
    - nome: String
    - descricao: String
    - valor: double
}

class Reserva {
    - id: Long
    - valor: double
}

class Pagamento {
    - id: Long
}

class CartaoCredito {
    - id: Long
    - titular: String
    - validade: Date
    - numero: int 
    - codigoVerificacao: String
}

class CupomDesconto {
    - id: Long
    - codigo: String
    - descricao: String
    - valor: double
    - dataValidade: Date
}

class Avaliacao {
    - id: Long
    - titulo: String
    - descricao: String
    - rate: String
    - divulgacao: bool
}

class Mensagem {
    - id: Long
    - email: String
    - nome: String
    - telefone: String
    - descricao: String
    - assunto: String
    - autenticado: boolean
}

Usuario "1" *--> "*" Contato
Usuario "1..0" --> "*" Mensagem
Usuario "*" --> "*" Perfil
Usuario "1" *--> "*" CartaoCredito
Usuario "1" o--> "*" Avaliacao
Usuario "1" *--> "*" Reserva
Reserva "1" o--> "1" Pagamento
Pagamento "1" o--> "1" CartaoCredito
Reserva "1" --> "*" ReservaQuarto
ReservaQuarto "1" o--> "*" Servico
ReservaQuarto "1" o--> "*" Quarto
Quarto "1" o--> "*" Amenidade
Quarto "1" o--> "1" TipoQuarto
Promocao "1" *--> "*" TipoQuarto
CupomDesconto "1" *--> "*" TipoQuarto


@enduml




